// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230727013212_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Usuario", b =>
                {
                    b.Property<int>("Handle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HANDLE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Handle"));

                    b.HasKey("Handle");

                    b.ToTable("USUARIO");
                });
#pragma warning restore 612, 618
        }
    }
}
